# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ea1eb825d7d4fe58cca224129ce25f46a3437381c96ba2759c7eb73c0ebfb6b729906812754d318ee9fde201769d53d8ad5a3a37c945445a473e4008a88cdc

test:
  secret_key_base: 064f96e03e1894a9a0e0f30b44f3c054dcab52c3e897efd1b2da82e04c1fc896ee7c40db6f5a0ca11df0c6040b1492165ad1bbd75c5466844663529de0fec82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
